### ISSUE TITLE
Python wrapper

### ISSUE THREAD

**Issue by Te-k** [Grey-Noise-Intelligence/api.greynoise.io#9]
I like the idea, just started a python wrapper for the API here : https://github.com/Te-k/pygreynoise

Keep up the good work ! :clap:

**Comment by andrew-morris** [comment]
This is absolutely incredible! Let me know what I can do to help!

**Comment by Te-k** [comment]
Thanks for the messages on Twitter. Feel free to propose Pull requests and ping me if the API is changing and there is a need to update the library

**Comment by andrew-morris** [comment]
@Te-k you got it man! I actually went ahead and wrote up some feedback for you, but I'll definitely take a wack at a PR a week from now. I'm kind of sort of on vacation at the moment so my computer time is limited until I get back to normal next week.

Here were my quick thoughts:

- User experience is completely smooth, but identical to curl + jq
- The real magic will be lots of different output methods
    - CSV
    - JSON
    - Greppable
    - Pprint
    - You name it
- There's a hidden feature that allows you to include an API key POST param to increase the amount of results you get from 500 to 5,000. I'll add a config file.
- Read IPs from a file
- Write results to a file

FUTURE FEATURES

These are features that I'm building into the `v1.1` API, but that are not developed yet. I'll give you early access to this so that we can get in sync before I announce the release.

- Going to separate out the categories of tags
    - Actors
    - Activity
    - Hosting
    - Worms
    - Tools
    - Search Engines
- Allow queries based on
    - CIDR (maybe)
    - Organization
    - ASN
    - rDNS
    - Datacenter
- Combination tag queries
    - e.g. TELNET_WORM_HIGH + RESIDENTIAL
    - or NTP_SCANNER_HIGH - SHODAN (maybe)
- Stats query
    - How many entries of a given tag were generated today? This week? This month?
- Metadata query
    - What does this analytic *actually mean*?
    - What are some reference pages for this analytic

Thanks again for all your work so far! I'm amped to grind out some code when I'm back online.

**Comment by Te-k** [comment]
That's great !
I have added all these suggestions to issues : https://github.com/Te-k/pygreynoise/issues
Also if you want I can move the repo to the Grey-Noise-Intelligence group, so that you have control on it and are not dependent on me if I don't have time to work on it (also it will help people to see that it is the official py library). Only thing I would like is to have still access to the repo so that I can help improving the library
